[module]
  [module.hugoVersion]
    extended = true
    min = "0.153.0"

  # Import official Bootstrap Icons repository
  [[module.imports]]
    path = "github.com/twbs/icons"

    # Mount Bootstrap Icons webfonts
    [[module.imports.mounts]]
      source = "font/fonts"
      target = "static/webfonts"

    # Mount Bootstrap Icons SCSS
    [[module.imports.mounts]]
      source = "font"
      target = "assets/scss/modules/bootstrap-icons"
      includeFiles = ["*.scss"]

    # Mount Bootstrap Icons SVGs
    [[module.imports.mounts]]
      source = "icons"
      target = "assets/svgs/bi"

  # Mount module's own assets and layouts
  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  # Import FontAwesome module
  [[module.imports]]
    path = "github.com/gethinode/mod-fontawesome/v5"

[params.modules.bootstrap-icons]
  integration = "core"
