baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-bootstrap-icons'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[module]
  # Build and serve using local mod-bootstrap-icons clone declared in the named Hugo workspace:
  workspace = "mod-bootstrap-icons.work"
  # replacements = 'github.com/gethinode/mod-fontawesome/v5 -> /Users/mark/Development/GitHub/gethinode/mod-fontawesome'
  [[module.imports]]
    path = "github.com/gethinode/mod-bootstrap-icons"
  [[module.imports]]
    path = "github.com/gethinode/mod-fontawesome/v5"

[params.modules.fontawesome]
  mode = "symbols"
  debug = false
  skipMissing = false
